// Generated by https://quicktype.io

import { IRequestStatus } from "../../../Shared/Utils/interfaces";

export interface ProfileSlice {
  profiles: Profiles[];
  status: IRequestStatus;
}

export interface Profiles {
  id: number;
  name: string;
  nationality: string;
  date_of_birth: string;
  photo: string;
}
